#include <cmath>
#include <cstdio>
#include <vector>
#include <iostream>
#include <algorithm>
using namespace std;

int cnt(long long num){
    int ans =1;
    for(int j= 2; j*j <=num; j++){
        if(num%j == 0){
            int count = 0;
            while(num%j == 0){
                num /= j;
                count++;
            }
            ans *= (count+1);
        }
    }
    if(num > 1) ans *= 2 ;
    return ans;
}

int main() {
    int t;
    cin>>t;
    while(t--){
        int n;
        cin>>n;
        
        long long k = 1;
        while(true){
            int a = k/2;
            int b = k+1;
            if(k%2){
                a = k;
                b = (k+1)/2 ;
            }
            long long div = cnt(a)*cnt(b);
            if(div > n){
                cout<<(k*(k+1)/2)<<endl;
                break;
            }
             k++;
        }
    }  
    return 0;
}
What is the value of the first triangle number to have over  divisors?

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7 'th triangle number would be 28 = 1 + 2 + 3 + 4 + 5 + 6 + 7. The first ten terms would
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...